name = "rallyflare"
main = "src/index.ts"
compatibility_date = "2025-10-08"

[vars]
WEBHOOK_USERNAME = "Rick"
WEBHOOK_PASSWORD = "123"

[[d1_databases]]
binding = "DB"
database_name = "rally-database"
database_id = "d80adc3d-40bf-4371-954b-884527f2a2c9"

[[services]]
binding = "MAILER"
service = "rally-mailer"

[[services]]
binding = "AI"
service = "rally-ai"

[[services]]
binding = "ATTACHMENTS"
service = "rally-attachments"
